version: '3.7'
services:
  sample:
    container_name: graph-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - REDIS_CRED=<redis_key>
      - NEO4J_CRED=<neo4j_cred>
      - S2AG_KEY=<s2ag_key>