neo4j:
  connectionUri: neo4j+s://588ce1ae.databases.neo4j.io
  username: neo4j
  instanceName: Instance01
redis:
  connectionUri: redis-11919.c124.us-central1-1.gce.cloud.redislabs.com:11919
  username: arxivinsanity
  database: 0
s2ag:
  buffer: "&limit=30"
  urlRoot: https://api.semanticscholar.org/graph/v1/paper/
  paperUrlFields: ?fields=year,citationCount,title,authors
  citationUrlFields: /citations?fields=paperId,isInfluential
  referenceUrlFields: /references?fields=paperId,isInfluential
graph:
  depth: 3
  refBreadth: 2
  citBreadth: 2
service:
  baseUrl: "http://localhost:8081"
