neo4j:
  connectionUri: "neo4j+s://588ce1ae.databases.neo4j.io"
  username: neo4j
  instanceName: Instance01
s2ag:
  urlRoot: "https://api.semanticscholar.org/graph/v1/paper"
  paperUrlFields: "?fields=year,citationCount,title,authors"
  citationUrlFields: "/citation?fields=paperId,isinfluential"
  referenceUrlFields: "/references?fields=paperId,isinfluential"