neo4j:
  connectionUri: neo4j+s://588ce1ae.databases.neo4j.io
  username: neo4j
  instanceName: Instance01

s2ag:
  buffer: "&limit=30"
  urlRoot: https://api.semanticscholar.org/graph/v1/paper/
  paperUrlFields: ?fields=year,citationCount,title,authors
  citationUrlFields: /citations?fields=paperId,isInfluential
  referenceUrlFields: /references?fields=paperId,isInfluential

graph:
  depth: 2
  refBreadth: 2
  citBreadth: 2
